#!/bin/sh

set -e

case "$1" in
    configure)
    if which update-grub2 > /dev/null 2>&1
    then
        LC_ALL=C update-grub2 || echo "Could not update grub, skipping."
    fi

    if [ -f /etc/default/grub ]; then
        sed -i "s/GRUB_GFXMODE=.*/GRUB_GFXMODE=auto/g" /etc/default/grub 
    fi

    if [ -f /etc/hamonikr/adjustments/10-adjust-grub-title.execute ]
    then
        /etc/hamonikr/adjustments/10-adjust-grub-title.execute
    fi
    ;;

    abort-upgrade|abort-remove|abort-deconfigure)

    ;;

    *)
        echo "postinst called with unknown argument \`$1'" >&2
    ;;
esac

